### ISSUE TITLE
Use the new Action API in Sketch 3.8 : )

### ISSUE THREAD

**Issue by bomberstudios** [romashamin/compo-sketch#1]
Awesome job with the Plugin, congrats from the team! : )

We've just released a beta for Sketch 3.8 with support for our new Action API, that allows you to run a Plugin in response to user actions, and it would be a very good fit for this.

Check http://developer.sketchapp.com/blog/2016-05-12-plugin-news/ for more info, and don't hesitate to ping us at developers@sketchapp.com if you need more info!

**Comment by romashamin** [comment]
@bomberstudios thank you, I’ve already checked out Action API and to be honest I’m very excited :)

Say thanks to the team for these features from me!
