### ISSUE TITLE
Combine it with "Dynamic Reposition"

### ISSUE THREAD

**Issue by atillacode** [romashamin/compo-sketch#10]
Hi,

thank you for this great plugin. 
One great feature would be to give the elements witdth and height  values.

For our GUI for android elements we use compo in combination with dynamic reposition plugin to achieve the following result:

![btn](https://cloud.githubusercontent.com/assets/16116689/17883418/b49a31bc-6912-11e6-8920-aba0c8e0c531.gif)

Basically we run:
1. Compo plugin after we change the length of the text to align the background (padding box)
2. Dynamic Reposition plugin to align the actual button background

**Comment by romashamin** [comment]
Hi, @helloatilla. Thanks for the issue.

I didn’t understand your task. Could you please explain it again?

**Comment by atillacode** [comment]
I have to admit that it's not easy to explain, sorry.

Is it possible to add another "BG" into the compo folder and to give it different values like "w:100%" and "h:100%" and padding values
- \- Folder
- -- Text with padding values
- -- BG 1 w:100% h:100% (related to BG 2) and add padding t:6 b:6 (layer is hidden)
- -- BG 2 (visible actual background for the text)

Does this make sense?

**Comment by romashamin** [comment]
@helloatilla maybe if you put a button’s folder into a container’s folder it will work?

<img width="450" alt="compo-issue-10" src="https://cloud.githubusercontent.com/assets/1148914/17891523/6b2e296c-694d-11e6-91bc-1905676875d4.png">

**Comment by atillacode** [comment]
Thank you, i wasn't aware of just creating another folder and BG. 👍
