### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [romashamin/compo-sketch#15]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by romashamin** [comment]
@bomberstudios hey, I’m trying out all the new updating things and a bit confused about `Startup`/`Shutdown` actions handlers.

The test plugin is here: https://github.com/romashamin/sketch-updating-plugins/blob/master/Updating%20Plugins.sketchplugin/Contents/Sketch/Updating%20Plugins.js

Looks like `onStartup` never calls so I always get **Updating Plugins _undefined_ is saying: Hello!** message.

Where I’m wrong?

**Comment by bomberstudios** [comment]
I think we've fixed that issue recently, let me confirm it on an internal build…

**Comment by bomberstudios** [comment]
Ok, you have a few things wrong in your plugin. I'll try to explain them:

- event names: you should be using `Startup` and `Shutdown`, instead of `Startup.finish` and `Shutdown.finish`
- you have code in the `Run` event that tries to access a variable defined on the `Startup` context, and that will be undefined, since variables are not shared between contexts.
- the idea is that we'll call the `Shutdown` event on the plugin that's being updated, and the `Startup` on the plugin that is installed. This doesn't work as expected on Sketch 45, but has been fixed in Sketch 46.

**Comment by romashamin** [comment]
> we'll call the Shutdown event on the plugin that's being updated, and the Startup on the plugin that is installed

Got it, thanks. So they are not necessary in my plugins.

@bomberstudios
