### ISSUE TITLE
Sketch 45 Issues

### ISSUE THREAD

**Issue by thebillettestate** [romashamin/compo-sketch#17]
Love your plugin but it all seemed to stop working last week when I downloaded the most recent Sketch update. I'm currently on 45.1 and still no results. 

Selecting text and activating the plugin simply doesn't do anything anymore. Also, I can no longer resize shapes from past Sketch files that were built back with Compo.

Please help! I'm in the middle of a major UI project that would benefit incredibly (and save me a ton of time) from your plugin.

**Comment by JWhiteUX** [comment]
I deactivated Compo and started using https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5

waiting on compo to be updated

**Comment by romashamin** [comment]
@thebillettestate did you [install updated Compo](https://github.com/romashamin/compo-sketch#install)?

**Comment by romashamin** [comment]
Now Compo supports Sketch 45 plugin updating system.
