### ISSUE TITLE
Doesn't work, instructions?

### ISSUE THREAD

**Issue by ckizer** [romashamin/compo-sketch#3]
I make a new text layer. I click command+J the layer name changes to some number values. No button is created. I tried grouping a rectangle and text layer and selecting group and hitting command+J. Group gets a new name. Can't resize button then hit command+J.

What am I missing?

Sketch 3.8

**Comment by romashamin** [comment]
@ckizer current version of the plugin obviously works only under the current version of Sketch.

Compo for Sketch 3.8 Beta [is here](https://github.com/romashamin/compo-sketch/tree/sketch-3.8).
