### ISSUE TITLE
Unable to use plugin with update to Sketch 3.8

### ISSUE THREAD

**Issue by danielthall** [romashamin/compo-sketch#5]
First, I'm a huge fan of this plugin, so thank you. Unfortunately, after updating to Sketch 3.8 this morning, the plugin no longer seems to work. When I try to run the plugin, either with `⌘J` or by running the plugin from the plugins menu, the layer does change the text layer name to `12:18:12:18` but no group or background layers are created. Screenshot attached:

<img width="223" alt="screen shot 2016-05-19 at 11 17 27 am" src="https://cloud.githubusercontent.com/assets/3289616/15401008/503aea22-1db3-11e6-9613-e0e4448f55bb.png">

**Comment by romashamin** [comment]
@danielthall thank you!

Make sure you [have updated the plugin](https://github.com/romashamin/compo-sketch#install) for version 3.8.

If you’re using the last version of the plugin and it still doesn’t work, please, let me know.

**Comment by danielthall** [comment]
That did it! Sorry for the false alarm and thanks!
