### ISSUE TITLE
Stopped working correctly

### ISSUE THREAD

**Issue by drkanukie** [romashamin/compo-sketch#7]
Sketch version 3.8.1

The text block label is created correctly but the UI/component group and background BG rect layers are not created since the last Sketch updates. Have to manually create the right group and BG layer now.

**Comment by romashamin** [comment]
@drkanukie it is always a good idea to check out [closed](https://github.com/romashamin/compo-sketch/issues/5) [issues](https://github.com/romashamin/compo-sketch/issues/6) before creating new one.

**Comment by drkanukie** [comment]
Thanks for the hint. One question when installing the 3.8 version it says it's the same version 1.1 which is confusing as I was expecting a different version of the plugin for 3.8 compatible version 1.2 or something like that.
