### ISSUE TITLE
Request: Don't rely on BG layer name

### ISSUE THREAD

**Issue by megaroeny** [romashamin/compo-sketch#8]
Either mention it in your Readme that the background layer needs to be named _BG_, or ideally don't have the plug-in rely on that name. Something I liked better about Relabel Button plug-in. 

I thought the plug-in had a bug, since it was making a new background layer even though I had one. then I renamed it to _BG_ and it worked for my existing background.

Challenge for you, thanks! 😉

**Comment by romashamin** [comment]
You can find all the nuances, like ‘BG’ thing, in [the following blog post](https://evilmartians.com/chronicles/compo-sketch).
